version: '3.7'
services:
  db:
    container_name: playground_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=playground
      - POSTGRES_DB=playground
      - POSTGRES_PASSWORD=playground
    volumes:
      - ./.database-data:/var/lib/postgresql/data/
volumes:
  database-data:
